package com.deployment.gitlab.service;

import com.deployment.gitlab.model.DeploymentRequest;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.stereotype.Service;

import java.time.format.DateTimeFormatter;

/**
 * Service for sending emails
 */
@Service
@RequiredArgsConstructor
@Slf4j
public class EmailService {

    private final JavaMailSender mailSender;

    @Value("${deployment.email.to}")
    private String deploymentEmail;

    @Value("${deployment.email.from}")
    private String fromEmail;

    @Value("${deployment.email.subject-prefix}")
    private String subjectPrefix;

    @Value("${SMTP_USERNAME:}")
    private String smtpUsername;

    /**
     * Sends a deployment request email
     */
    public void sendDeploymentRequest(DeploymentRequest request) {
        // Demo mode if SMTP is not configured
        if (smtpUsername == null || smtpUsername.isEmpty()) {
            log.warn("⚠️  DEMO mode - SMTP not configured");
            log.info("=== DEPLOYMENT EMAIL (not sent) ===");
            log.info("To: {}", deploymentEmail);
            log.info("From: {}", fromEmail);
            log.info("Subject: {} {}", subjectPrefix, request.getTargetEnvironment());
            log.info("=== BODY ===");
            log.info(buildEmailBody(request));
            log.info("=== END EMAIL ===");
            log.info("💡 Configure SMTP_USERNAME, SMTP_PASSWORD and SMTP_HOST to send real emails");
            return;
        }

        try {
            log.info("Sending deployment request to {}", deploymentEmail);

            SimpleMailMessage message = new SimpleMailMessage();
            message.setFrom(fromEmail);
            message.setTo(deploymentEmail);
            message.setSubject(subjectPrefix + " " + request.getTargetEnvironment());
            message.setText(buildEmailBody(request));

            mailSender.send(message);

            log.info("Deployment email sent successfully");
        } catch (Exception e) {
            log.error("Error sending deployment email", e);
            throw new RuntimeException("Email sending failed: " + e.getMessage());
        }
    }

    /**
     * Builds the email body
     */
    private String buildEmailBody(DeploymentRequest request) {
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        StringBuilder body = new StringBuilder();
        body.append("New deployment request\n");
        body.append("=" .repeat(50)).append("\n\n");

        body.append("Requester: ").append(request.getRequesterName()).append("\n");
        body.append("Email: ").append(request.getRequesterEmail()).append("\n");
        body.append("Date: ").append(request.getRequestDate().format(formatter)).append("\n");
        body.append("Target environment: ").append(request.getTargetEnvironment()).append("\n\n");

        body.append("Applications to deploy:\n");
        body.append("-".repeat(50)).append("\n");
        for (String appName : request.getApplicationNames()) {
            body.append("  • ").append(appName).append("\n");
        }

        if (request.getNotes() != null && !request.getNotes().isEmpty()) {
            body.append("\nNotes:\n");
            body.append("-".repeat(50)).append("\n");
            body.append(request.getNotes()).append("\n");
        }

        body.append("\n").append("=".repeat(50)).append("\n");
        body.append("Automated email generated by GitLab Deployment Manager\n");

        return body.toString();
    }
}
